### ISSUE TITLE
Feature Request: Unlisted articles

### ISSUE THREAD

**Issue by GiovanH** [getpelican/pelican#2865] opened 2021-04-16 02:43 UTC
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

Currently, pages can be given the `status: hidden` attribute, which publishes them to the standard location but doesn't include them in page listings. This is great for making unlisted pages, or error pages. 

Articles also have a `status: hidden` attribute, but unlike pages this keeps them from being included in the output at all. You can set articles as `drafts`, but all drafts get lumped together in the `drafts` folder by default

I propose an `unlisted` status for articles that would behave the same as pages' `hidden` status: they would be output to the standard path, but not be included by default in listings (including tags, categories, and chrono)

If this seems like a useful addition, I am interested in helping to implement it.

**Comment by justinmayer** [comment] 2021-04-16 07:12
Hey Gio. This is a duplicate of #1965, which nobody stepped forward to implement. Regarding the following comment…

> You can set articles as `drafts`, but all drafts get lumped together in the `drafts` folder by default

As @avaris [mentioned](https://github.com/getpelican/pelican/issues/1965#issuecomment-495945811) in the aforementioned issue, you should be able to use `DRAFT_URL/DRAFT_SAVE_AS` to place drafts where you want.

That said, I can't think of any reason why setting `Status: hidden` for articles shouldn't behave in a similar fashion as it does for pages, and your offer to implement that feature parity for articles is much appreciated. Would you please submit a pull request when you have a solution ready for review? 😁

**Comment by GiovanH** [comment] 2021-04-16 07:31
I would be worried about changing the behavior of “hidden”, which currently has a different effect than unlisted (although the behavior technically seems undefined?). Not as catastrophic as automatically revealing hidden posts publicly, but still possibly undesirable behavior

**Comment by justinmayer** [comment] 2021-04-16 07:38
If setting `Status: hidden` causes articles not to be generated at all, then that seems like unintended behavior that I don't feel we need to preserve.

Since there's already an existing issue for this topic, I'm closing this one in favor of the pre-existing issue.

**Closed by justinmayer** 2021-04-16 07:38 UTC
Labels: enhancement
