### ISSUE TITLE
--write-selected doesn't work as expected

### ISSUE THREAD

**Issue by andreamoro** [getpelican/pelican#2957] opened 2021-12-04 10:15 UTC
I am trying to generate a specific file as per the [instructions](https://docs.getpelican.com/en/stable/publish.html#site-generation). The output path, recovered with the --debug option, is ignored.
The cli output states all files are processed, but the output folder results clean (because the delete output folder is wiped as per the settings).

![image](https://user-images.githubusercontent.com/5256583/144705737-eeab7202-309b-4a52-ab1c-cd0d085f0ebc.png)

I've tried all the following combinations:
```
pelican --write-selected output/css/css-articolo-it.html  
pelican --write-selected output/css/
pelican --write-selected output/css
pelican --write-selected /home/andrea/GitHub/websites/andreamoro-ssg-python/website/output/css/css-articolo-it.html 
```

**Comment by avaris** [comment] 2021-12-04 11:59
Duplicate of #2678.

**Closed by avaris** 2021-12-04 11:59 UTC
