### ISSUE TITLE
Read and write only files modified in working directory

### ISSUE THREAD

**Issue by NickC5163** [getpelican/pelican#3206] opened 2023-10-13 14:51 UTC
- [X] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [X] I am willing to lend a hand to help implement this feature. 

## Feature Request

I work with a very large Pelican doc set (almost 1000 pages) and build times take around 2 minutes. This is great for remote builds but for local server builds where I am editing a small handful of files at a time, this build time is not very feasible.

Testing and investigation show that `--write-selected` does not work (https://github.com/getpelican/pelican/issues/2678) and caching does not reduce build times very much for such large doc sets.

Is there any way we can get a feature for local development that can be used to only Read and Write files that Git reports as unstaged changes since the last commit? Essentially a directive that would tell Pelican (after building the entire docset once) to only monitor and write specific files?

**Comment by justinmayer** [comment] 2023-10-13 15:24
Hey @NickC5163. I can certainly empathize with your desire to reduce your build time. As you've seen in the issue you linked to, folks there have discussed a variety of alternative solutions to replace what `--write-selected` was designed to achieve. You appear to be proposing another alternative method based on Git, working tree states, and detecting files that Git considers to be modified. While I think an easier entry-level solution would be to specify the relative path to the source file and only generate that file, ultimately whoever decides to volunteer to implement a solution will have significant influence regarding which approach to take. Speaking of which, regardless of the specific approach, would you be interested in helping out with implementing a way to reduce build times?

Rather than create a new issue, I'd prefer to consolidate this discussion in the aforementioned linked issue since it is already the place where people are talking about various ways in which to handle build time reduction.

**Comment by NickC5163** [comment] 2023-10-13 15:30
Thanks @justinmayer Will keep all discussions over there:)

**Comment by zemichael1234** [comment] 2023-10-14 09:24
how do i contribute to the project and looking for collaboration if any of you guy got some idea tell me

**Comment by pauloxnet** [comment] 2023-10-14 11:23
> how do i contribute to the project and looking for collaboration if any of you guy got some idea tell me

Please read the "Contributing and feedback guidelines"
https://docs.getpelican.com/en/latest/contribute.html

**Comment by justinmayer** [comment] 2023-10-24 07:24
Closing in favor of pre-existing issue, as noted previously.

**Closed by justinmayer** 2023-10-24 07:24 UTC
Labels: enhancement
