### ISSUE TITLE
make clean should empty cache

### ISSUE THREAD

**Issue by danmackinlay** [getpelican/pelican#1762] opened 2015-06-18 11:46 UTC
#1742 and #1722 both mention the confusing behaviour of corrupted caches.

It is perhaps counterintuitive that the default makefile does not empty the cache, just the environment.

For the sake of intuitiveness, it would be wise to clear the cache too when one does a `make clean`

**Comment by howthebodyworks** [comment] 2015-06-18 11:48
FWIW, I know that this cache thing is regarded as an upgrade issue, but I get occasional AttributeErrors like #1722 from non-reproducible transient cache corruption; easing cache nuking looks like an easy win compared to fixing transient cache errors, esp given #1759.

**Comment by justinmayer** [comment] 2015-07-27 16:35
Hi Dan. Thanks for your comments. Is something you would like to work on?

**Comment by ingwinlu** [comment] 2015-08-10 14:14
the cache directory is configurable (`CACHE_PATH`), so 'guessing' a directory in the Makefile is a no-go for me. To realize that we would need to add a command line argument to pelican itself which parses the configuration for the cache directory and deletes it.

**Comment by leotrs** [comment] 2016-08-01 16:10
@ingwinlu if there's still interest in this (it sounds good to me), I could try to prepare a PR at some point (no promises).

**Comment by justinmayer** [comment] 2016-08-01 18:52
> it would be wise to clear the cache too when one does a make clean

Seems sensible enough to me.

@leotrs: Would welcome a PR to that effect if you can spare the time.  (^_^)

**Comment by leotrs** [comment] 2016-08-01 18:57
As per @ingwinlu's comment, the cleanest way I can see this happening is asking pelican to parse the config file and outputting the `CACHE_PATH`, so make clean can just run ```rm `pelican --output-cache-path```` or some such. Is that the way we want to go?

**Comment by justinmayer** [comment] 2016-08-01 19:16
@leotrs: Seems like a fine approach to me.

**Comment by leotrs** [comment] 2016-08-01 20:19
While we're at it, we can have a `pelican --read-config-file` and dump the whole final settings dict. This could be useful in debugging. Then, `make clean` can just `grep` the output and do its thing.

**Comment by leotrs** [comment] 2016-08-01 23:07
@justinmayer, [I added the](https://github.com/getpelican/pelican/pull/1984) `--dump-settings` command line argument, with the aforementioned functionality. Run from the `pelican/tests` folder in the main repository:
```
tests $ pelican -s default_conf.py --dump-settings 'GITHUB_URL'
'http://github.com/ametaireau/'
```

Then I tried to edit the Makefile as requested, but my bash is failing me. I tried to do the following, without success.
```
clean:
	[ ! -d $(OUTPUTDIR) ] || rm -rf $(OUTPUTDIR)
	CACHEPATH=$(pelican --dump-settings 'CACHE_PATH')
	[ ! -d $(CACHEPATH) ] || rm -rf $(CACHEPATH)
```

**Comment by leotrs** [comment] 2016-08-11 23:49
Update:

* Haven't revisited my failed attempt at modifying the Makefile.
* The PR is stand-alone and I think could be merged at least as a debugging tool.
* It could also be used for further Makefile integration. Example follows.
    The `$OUTPUTDIR` variable inside Makefile is set during `pelican-quickstart`. If the user changes `OUTPUT_PATH` in `pelicanconf.py`, Makefile has no way to know this. If the PR is merged, we could always read the settings file to look for `OUTPUT_PATH` and/or `CACHE_PATH` and delete the correct ones.

**Comment by ingwinlu** [comment] 2016-08-12 05:44
your Makefile snippet won't work because it is a Makefile, not a Bash script. In a Makefile rule each line is executed independently of the others, hence you set CACHEPATH in one subshell, but rm -rf (i don't like the -rf here) can not see it as it is also run in a new subshell.

```
CACHEPATH?=$$(PELICAN --dump-settings 'CACHE_PATH')

clean: clean-output clean-cache

clean-output:
    [ ! -d $(OUTPUTDIR) ] || rm -rf $(OUTPUTDIR)

clean-cache:
    [ ! -d $(CACHEPATH) ] || rm -rf $(CACHEPATH)
```

However I am still against merging something like that. It is prone to errors and a Makefile is easily extended to cover the cache deletion if needed.

**Comment by leotrs** [comment] 2016-08-12 13:09
I see. Thanks for the clarification. The original Makefile executes `[ ! -d $(OUTPUTDIR) ] || rm -rf $(OUTPUTDIR)` for the `clean` recipe, I just added a similar one for the cache directory.

I agree it doesn't seem super safe.

**Comment by justinmayer** [comment] 2018-10-26 16:15
The `--print-settings` flag is now in master, which should help with debugging.

As for the original issue description... As @ingwinlu intimated, any automation that comes bundled with Pelican (Makefile, Invoke script, etc) is for convenience and is not high priority in the context of Pelican core development. In the end, it's up to end users to customize said automation to their liking. Any pull requests that help improve that automation in a universally applicable manner are of course always welcome.

**Closed by justinmayer** 2018-10-26 16:15 UTC
