### ISSUE TITLE
double quotes not always picked up by TYPOGRIFY in ReST documents

### ISSUE THREAD

**Issue by howthebodyworks** [getpelican/pelican#1541] opened 2014-11-20 13:01 UTC
In my blog, double quotes never get the Smartypants treatment despite TYPOGRIFY=True in my settings file. Not sure if this is code, documentation or PEBCAK error. First, let's see if I'm crazy.

`quote_test_1.rst` contains the following:
````
:title: quote test 1
:date: 2014-11-20 13:27:54 +0100

'This' is some "content" -- so --- I --- claim.
````
The resulting page on my blog is
![screen shot 2014-11-20 at 13 40 08](https://cloud.githubusercontent.com/assets/21740/5124688/e20b9426-70ba-11e4-901f-07167dec42dd.png)
Single quotes and dashes are "smartified" but double quotes are not.

On the other hand, `quote_test_2.md` contains the following:
````
Title: quote test 2
Date: 2014-11-20 13:30:32 +0100

'This' is some "content" -- so --- I --- claim.
````
![screen shot 2014-11-20 at 13 32 44](https://cloud.githubusercontent.com/assets/21740/5124613/010a6cfe-70ba-11e4-8fa7-114cd1711cd7.png)
Single quotes, dashes *and* double quotes are "smartified".

AFAICT the settings to choose which smartypants transformations to apply are *not* exposed, so this shouldn't really be happening.

Running current pelican master, which corresponds to the 3.5.0 release version.

* smartypants==1.8.6
* typogrify==2.0.7
* python==2.7.5

Unit tests pass, although I couldn't work out how to tell if the typogrify filter test (which does doest for double quote substitution in ReST) was being skipped. I'll return later to work that out.
````
$ python -m unittest discover
.....................................................................ssssssssssssssssss............................................................
----------------------------------------------------------------------
Ran 147 tests in 5.900s

OK (skipped=18)
````

Is anyone else experiencing this issue?

-Dan

**Comment by johnmastro** [comment] 2015-02-12 00:34
I also noticed this. As far as I can tell, the issue is that `docutils` has already replaced the double quotes with `&quot;` by the time `typogrify` and `smartypants` see them.

However, I don't have enough knowledge of the various pieces to say whether that's a mistake or if there's an easy fix for it. Perhaps `smartypants` should optionally perform the replacement on the `&quote;` entities, or maybe there's a way to prevent `docutils` from replacing the double quotes at the beginning.

**Comment by justinmayer** [comment] 2015-02-12 00:43
Good sleuthing. Anyone want to tackle this and come up with a fix?

**Comment by johnmastro** [comment] 2015-02-12 00:44
I dug a bit further and it turns out `smartypants` already has the ability to process the HTML entities.

    import smartypants

    # Won't convert the HTML entities
    smartypants.smartypants("foo &quot;bar&quot; baz")
    # => 'foo &quot;bar&quot; baz'

    # Will convert the HTML entities
    attr = smartypants.default_smartypants_attr | smartypants.Attr.w
    smartypants.smartypants("foo &quot;bar&quot; baz", attr=attr)
    # => 'foo &#8220;bar&#8221; baz'

The `Attr` business seems to be the way you enable or disable `smartypants` functionality.

If nobody sees a problem with doing this, I'd be happy to turn it into a PR.

**Comment by justinmayer** [comment] 2015-02-12 00:55
Fine by me. Anyone else want to comment?

**Comment by johnmastro** [comment] 2015-02-12 02:49
@justinmayer, this will also require a change to the functions `typogrify` and `applyfilters` in `typogrify.filters`. Specifically, they'll need to take an argument telling them whether to request this special behavior from `smartypants`.

My first thought is that it would be best to have them take an optional keyword arg (e.g. `include_entities`) rather than expose the `Attr` stuff in `smartypants`. What do you think?

I'll do a PR for this too but wanted to get your take first, since I see you're involved there too.

**Comment by avaris** [comment] 2015-02-12 06:48
@johnmastro not necessarily. You can just set the `smartypants.Attr.default` and `typogrify.filters.typogrify` will use that:

```python
>>> from typogrify.filters import typogrify
>>> typogrify("foo &quot;bar&quot; baz")
'foo &quot;bar&quot;&nbsp;baz'
>>> import smartypants
>>> smartypants.Attr.default = smartypants.Attr.default | smartypants.Attr.w
>>> typogrify("foo &quot;bar&quot; baz")
'foo &#8220;bar&#8221;&nbsp;baz'
```

**Comment by johnmastro** [comment] 2015-02-12 23:54
Thanks @avaris, good point. I'll put something together based on that.

**Comment by johnmastro** [comment] 2015-02-13 00:32
I've now submitted this as PR #1627.

**Comment by justinmayer** [comment] 2015-02-16 18:45
Merged. Thanks, John!

**Closed by justinmayer** 2015-02-16 18:45 UTC
