### ISSUE TITLE
Match output paths with content paths

### ISSUE THREAD

**Issue by cup** [getpelican/pelican#2673] opened 2019-12-28 00:04 UTC
I have this setup:

~~~
content/number-types/index.rst
~~~

and I expect this result:

~~~
content/number-types/index.html
~~~

However I am not sure how to make that happen. First I set this:

~~~py
# pelicanconf.py
SLUGIFY_SOURCE = 'basename'
~~~

and I get this result:

~~~
CRITICAL: RuntimeError: File /tmp/output/index.html is to be overwritten
~~~

So I change to this setup:

~~~
content/number-types/readme.rst
~~~

and get this result:

~~~
output/readme.html
~~~

so then I try this:

~~~py
SLUGIFY_SOURCE = 'basename'
ARTICLE_SAVE_AS = '{slug}/index.html'
~~~

and get this result:

~~~
output/readme/index.html
~~~

How can I get Pelican to stop trying to be smart, and just replicate the paths
as I have them?

**Comment by justinmayer** [comment] 2019-12-28 06:38
If you remove the settings file changes mentioned above and instead add the following…
```
# Mirror content hierarchy to output hierarchy
PATH_METADATA= '(?P<path_no_ext>.*)\..*'
ARTICLE_SAVE_AS= '{path_no_ext}.html'
ARTICLE_URL= '{path_no_ext}.html'
PAGE_SAVE_AS= '{path_no_ext}.html'
PAGE_URL= '{path_no_ext}.html'
```
… does that result in the output you expect?

**Comment by cup** [comment] 2019-12-28 07:09
@justinmayer yes, looks like it works with just this:

~~~py
PATH_METADATA= '(?P<path_no_ext>.*)\..*'
ARTICLE_SAVE_AS = '{path_no_ext}.html'
ARTICLE_URL = '{path_no_ext}.html'
~~~

**Comment by justinmayer** [comment] 2019-12-28 09:07
@cup: Yes, but the `PAGE_*` settings are needed if one were to want the same behavior for pages.

**Comment by justinmayer** [comment] 2019-12-28 09:12
Duplicate of #686. Since the answer should be more visible, I documented the aforementioned solution via b8f2326f.

@cup: Rather than submitting a flurry of short-lived issues as questions arise, which results in extra noise for maintainers, in the future please consider reaching out via the Pelican IRC channel, as noted in the [How to Get Help](https://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!

**Closed by justinmayer** 2019-12-28 09:12 UTC

**Comment by cup** [comment] 2019-12-28 16:10
@justinmayer I came up with this one - removes extra part from the URL:

~~~py
PATH_METADATA = '(?P<dirname>.*)/(?P<basename>.*)\..*'
ARTICLE_SAVE_AS = '{dirname}/{basename}.html'
ARTICLE_URL = '{dirname}'
~~~
