### ISSUE TITLE
pelican-quickstart    raise an error.

### ISSUE THREAD

**Issue by crazy-canux** [getpelican/pelican#2073] opened 2016-12-26 08:46 UTC
python2.7 + Ubuntu14.04 + virtualenv1.11

 $pelican-quickstart                                                                            
Traceback (most recent call last):
  File "/usr/local/bin/pelican-quickstart", line 7, in <module>
    from pelican.tools.pelican_quickstart import main
  File "/usr/local/lib/python2.7/dist-packages/pelican/tools/pelican_quickstart.py", line 52, in <module>
    'lang': locale.getlocale()[0].split('_')[0],
AttributeError: 'NoneType' object has no attribute 'split'

Am I wrong?

**Comment by justinmayer** [comment] 2016-12-26 15:54
Dupe of issue #2043.

In the future, **please check existing issues before submitting an issue report**. Then, follow our docs on [how to get help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help), which clearly expresses a preference for our IRC channel. Thank you.

**Closed by justinmayer** 2016-12-26 15:54 UTC

**Comment by justinmayer** [comment] 2017-01-10 22:00
Pelican 3.7.1 has been released, containing a fix for this problem. Apologies for any frustration caused!

**Comment by crazy-canux** [comment] 2017-01-11 04:19
It's working.
Thanks!
