### ISSUE TITLE
pelican autoreload and listen together throws a TypeError exception

### ISSUE THREAD

**Issue by carlosperate** [getpelican/pelican#2674] opened 2019-12-28 13:47 UTC
When running pelican with the `autoreload` and `listen` flags together I get the following exception:

```
$  pelican -s pelicanconf.py --autoreload --listen
CRITICAL: TypeError: cannot pickle 'generator' object
```

Both flags work correctly when used individually.

Tested with Pelican 4.2.0, in macOS Mojave, and Python 3.8.0.

It can be replicated in a new project (full stack trace included below):

```
$ pelican-quickstart --path .
Welcome to pelican-quickstart v4.2.0.

This script will help you create a new Pelican-based website.

Please answer the following questions so this script can generate the files
needed by Pelican.

    
> Where do you want to create your new web site? [.] 
> What will be the title of this web site? test
> Who will be the author of this web site? author
> What will be the default language of this web site? [en] en
> Do you want to specify a URL prefix? e.g., https://example.com   (Y/n) n
> Do you want to enable article pagination? (Y/n) n
> What is your time zone? [Europe/Paris] 
> Do you want to generate a tasks.py/Makefile to automate generation and publishing? (Y/n) n
Done. Your new project is available at /Users/microbit-carlos/workspace/mine/deleteme

$ pelican -s pelicanconf.py --autoreload --listen -D
DEBUG: Pelican version: 4.2.0
DEBUG: Python version: 3.8.0
DEBUG: Adding current directory to system path
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Restoring system path
CRITICAL: TypeError: cannot pickle 'generator' object
Traceback (most recent call last):
  File "/Users/microbit-carlos/.local/share/virtualenvs/my-website-sjuBY4Hi/bin/pelican", line 8, in <module>
    sys.exit(main())
  File "/Users/microbit-carlos/.local/share/virtualenvs/my-website-sjuBY4Hi/lib/python3.8/site-packages/pelican/__init__.py", line 547, in main
    p1.start()
  File "/Users/microbit-carlos/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/microbit-carlos/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/microbit-carlos/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/microbit-carlos/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/microbit-carlos/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/microbit-carlos/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/microbit-carlos/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'generator' object
```

pip list output:

```
$ pip list
Package         Version
--------------- -------
blinker         1.4    
docutils        0.15.2 
feedgenerator   1.9    
Jinja2          2.10.3 
MarkupSafe      1.1.1  
pelican         4.2.0  
pip             19.3.1 
Pygments        2.5.2  
python-dateutil 2.8.1  
pytz            2019.3 
setuptools      42.0.2 
six             1.13.0 
Unidecode       1.1.1  
wheel           0.33.6 
```

**Comment by avaris** [comment] 2019-12-28 16:05
Looks similar to #2400

**Comment by carlosperate** [comment] 2019-12-28 16:42
It might be related and the problem looks like it's located in the same area more or less, but the error itself is quite different. Maybe same problem manifesting itself in different ways?
I tried the same with Python 3.6.8 and it works there, so it might be related to Python 3.8.

**Comment by hiphamster** [comment] 2020-01-25 04:00
Seeing identical issue, with 3.8.0

**Comment by jean** [comment] 2020-03-25 06:40
These bots that purport to clean things up usually just make extra work. In this case, the issue documented is as relevant as ever. Either that, or it has indeed been fixed. In either case, closing is not helpful. The issue will come up again, someone will add a duplicate issue, and maybe find the closed issue and reference it. Context will be lost (e.g. the original reporter won't be notified, links to the closed issue will become misleading).

Triaging old issues is a virtuous chore, but it has to be done with understanding, and it should not generate noise in the tracker --- e.g. it could be done using a date filter. 

(Copied from my comment on the Netlify tracker: https://github.com/netlify/netlify-cms/issues/1678#issuecomment-548769362)

**Comment by justinmayer** [comment] 2020-03-25 07:50
Hi @jean. Adding the stale bot is an experiment, and the jury is still out. Maybe it works out long-term, maybe not. That said, my current assessment is that the bot provides more value than it costs. For example, because the bot has brought this issue to my attention, it is now getting looked at again. Maybe that would have happened anyway, eventually, but that could have been many months from now — or longer.

Plus, there are tools in place to mitigate some of this bot's downsides. If we assign an issue or add it to a milestone — as I have now down for this issue — the bot will no longer mark the issue as stale.

**Comment by justinmayer** [comment] 2020-03-25 07:51
I have reproduced this problem on macOS 10.13.6 + Python 3.8.2 + Pelican master. The best workaround I can offer at the moment is to instead use [Invoke](https://docs.getpelican.com/en/stable/publish.html#invoke) and [LiveReload](https://github.com/lepture/python-livereload) :

1. Run `pelican-quickstart` to generate an up-to-date Invoke `tasks.py` file
2. `pip install invoke livereload`
3. `invoke livereload`

That said, on a long-term basis, it would be great to fix the underlying problem. Would anyone be willing to help out and try implementing an appropriate fix?

**Comment by jean** [comment] 2020-03-25 08:25
@justinmayer thank you for the considered response :grin: 
I'd still prefer an approach using a date filter to list languishing issues, but that's just my opinion. 

I didn't know about Invoke, looks cool :-)
It reminds me of [DoIt](https://pydoit.org/) (also Python).

**Comment by avaris** [comment] 2020-05-01 18:28
> Maybe something to do with the multiprocessing changes? https://docs.python.org/3/whatsnew/3.8.html#multiprocessing

Yes!

> On macOS, the *spawn* start method is now used by default. 

That's a major change and effectively makes this one duplicate of #2400. Solution is probably refactoring how watchers are handled.

**Comment by justinmayer** [comment] 2020-05-10 05:27
Thanks to tireless efforts by @avaris, this issue has been resolved and will be included in the next Pelican release.

**Closed** 2020-05-10 05:29 UTC

**Comment by carlosperate** [comment] 2020-05-10 15:17
That's fantastic, thank you @avaris and @justinmayer!

**Comment by pwc3** [comment] 2020-05-11 04:25
I have a potential workaround for users encountering this before the next release. I use this shell script to kick off two `pelican` subprocesses: one to `--autoreload` and one to `--listen`. It also launches Firefox to test — an optional step that can be excluded if you prefer. 

If you Ctrl-C, both `pelican` subprocesses are terminated.

```sh
#!/usr/bin/env bash

# Workaround for kicking off two subprocesses, allows you to quit both at once via Ctrl-C.
# See: https://spin.atomicobject.com/2017/08/24/start-stop-bash-background-process/
trap "kill 0" EXIT

# These need to be run separately to work around:
# https://github.com/getpelican/pelican/issues/2674
pelican --autoreload &
pelican --listen &

# Launch Firefox to load the page.
open -a Firefox http://localhost:8000

# Wait for all background processes to finish.
wait
```
