### ISSUE TITLE
Please add a dark/black theme/template to the default installation

### ISSUE THREAD

**Issue by DragonSerW** [getpelican/pelican#3132] opened 2023-05-16 12:38 UTC
Hello!
I use latest Pelican (4.8.0 for now).
My experience with Pelican started today.

The question is: could you, authors, please add a dark/black theme/template to the default installation.
If this particular Theme will be light/dark adjustable like https://github.com/MrReSc/MindTheDark/ -- it will be much appreciated ))

I love the default theme, but it lucks black background.

**Comment by buanzo** [comment] 2023-06-11 21:05
Yes, please. See below how a pelican 4.8.0 with default theme looks like in "Microsoft Edge" Experimental Force-Dark feature. I think it's awesome.

![image](https://github.com/getpelican/pelican/assets/553167/9d1e9ea9-2c82-4d3d-b02b-386c6b250d99)

**Comment by DragonSerW** [comment] 2023-06-12 08:07
I found a black theme for Pelican: https://github.com/aleylara/Papyrus.
Steel need it badly to add this or some another theme to the default installation of Pelican :-))

**Comment by DragonSerW** [comment] 2023-10-24 21:36
Hello guys!
I ask you -- no I pray to you -- please add 'black & light' template to the _default_ installation of Pelican.
Now I use https://github.com/aleylara/Papyrus, but I can not write to the author of this template to fix some things in it.
For example: one need to install brew @ the machine where Pelican will be deployed.
As for Fedora or Debian it is not a good thing.
One should use macOS for HomeBrew, for sure.

**Comment by justinmayer** [comment] 2023-10-25 09:25
Hi SerW. A few thoughts, in no particular order:

* As far as I can tell, Homebrew is not required to use that theme. _Installing Stork_, on the other hand, does appear to be required. I believe Homebrew is only mentioned in that project’s README as one potential way to install Stork, but there are other ways to install Stork on Linux that do not require Homebrew.
* The crux of this issue (i.e., replacing the default theme) is essentially a duplicate of #1280. Ergo, I am inclined to close this issue in favor of that one.
* It’s clear that we need some themes that are maintained by the Pelican community as opposed to a single author. Otherwise themes fall into disrepair. I will raise this topic in the aforementioned issue.

**Comment by justinmayer** [comment] 2023-10-27 07:51
@DragonSerW: [Papyrus is now located under the Pelican Themes organization](https://github.com/pelican-themes/papyrus). The intention is to foster collaboration and not rely on a single person for improvements and maintenance.

> I can not write to the author of this template to fix some things in it.

I believe Aleylara intentionally disabled the "Issues" functionality in that repository in an attempt to (1) encourage folks to solve their own problems and submit pull requests, and (2) reduce administrative burden. As an open-source maintainer, I can relate to that sentiment. So for now, the "Issues" feature on the transferred repository remains disabled. If there is something that you think could be improved, I encourage you to submit a pull request to that repository along with a detailed rationalization and explanation of the proposed changes.

As an experiment, I have enabled the _Discussions_ feature on that repository. But that is really only meant as a last resort. Ultimately, themes are only going to be maintained if improvements are made by community members themselves — not by expectations that **someone else** will volunteer **their** time to fix problems that **other people** are having.

Having taken all the immediate steps I can to move this forward, I await your contributions to the [newly-relocated Papyrus repository](https://github.com/pelican-themes/papyrus). 💫

**Closed by justinmayer** 2023-10-27 07:51 UTC
