### ISSUE TITLE
Authors page generated when set it not to

### ISSUE THREAD

**Issue by randomhammer** [getpelican/pelican#1729] opened 2015-05-24 23:28 UTC
I am trying to set Pelican to not generate an authors page. If I use

AUTHOR_SAVE_AS = ""

I still get the page. If I use AUTHOR_SAVE_AS = None, per instructions in another bug fix, I get this

WARNING: AUTHOR_SAVE_AS is set to None
CRITICAL: 'NoneType' object has no attribute 'startswith'
make: *** [html] Error 1

Is there a way to not generate an authors page, since I will always be the only one?

**Comment by avaris** [comment] 2015-05-25 14:04
Which authors page are you talking about exactly? 

There is the page which lists all articles for a given author (generated by `author.html` in the theme). This is controlled by `AUTHOR_SAVE_AS`, so setting it to `''` (used to be `None` but not anymore) should get rid of them.

And there is also the page which lists all authors (generated by `authors.html` in the theme). This is controlled by `DIRECT_TEMPLATES`. Remove `'authors'` from it. Default is `('index', 'categories', 'authors', 'archives')`. So use `('index', 'categories', 'archives')`.

**Comment by justinmayer** [comment] 2015-06-15 22:10
@randomhammer: Were you able to resolve your issue? Please let us know.

**Comment by leotrs** [comment] 2016-08-01 16:12
@randomhammer: If there's still a problem (what you did works perfectly for me as of last week), please run `make clean` after implementing avaris' suggestion and then check if the author page is still generated.

Otherwise, I would close this as not able to reproduce.

**Closed** 2016-08-01 18:52 UTC
