### ISSUE TITLE
make devserver failing

### ISSUE THREAD

**Issue by cmcknight** [getpelican/pelican#2787] opened 2020-08-09 19:14 UTC
<u>Environment</u>
Computer: iMac
Operating System: MacOS 10.15.16
Python Version: 3.8.5
Pip Version: 20.2.1

<u>Step to Reproduce</u>
1. Ran pelican-quickstart
2. Attempted to make devserver (make devserver)

Received error message:

"pelican -lr /Users/chuck/mysites/senestone/content -o /Users/chuck/mysites/senestone/output -s /Users/chuck/mysites/senestone/pelicanconf.py
CRITICAL: TypeError: cannot pickle 'generator' object
make: *** [devserver] Error 1

**Comment by davidag** [comment] 2020-08-10 16:44
This seems to be a known issue on MacOS. Take a look at: https://github.com/getpelican/pelican/issues/2674#issuecomment-603692008

**Comment by avaris** [comment] 2020-08-10 17:37
Yes, this is a duplicate of #2674 and it is fixed in current master (via #2750).

**Closed by avaris** 2020-08-10 17:37 UTC
Labels: bug
