### ISSUE TITLE
pelican-quickstart failed to start

### ISSUE THREAD

**Issue by faraco** [getpelican/pelican#2070] opened 2016-12-23 12:09 UTC
System: Ubuntu 16.04
Python version: 2.7
pelican version: 3.7.0
Installation method: (pip) `sudo pip install pelican`

* Issue:running pelican-quickstart failed
    - traceback
```
$ pelican-quickstart
Traceback (most recent call last):
  File "/usr/local/bin/pelican-quickstart", line 7, in <module>
    from pelican.tools.pelican_quickstart import main
  File "/usr/local/lib/python2.7/dist-packages/pelican/tools/pelican_quickstart.py", line 52, in <module>
    'lang': locale.getlocale()[0].split('_')[0],
AttributeError: 'NoneType' object has no attribute 'split'
```

Is this a known issue?

**Comment by justinmayer** [comment] 2016-12-23 13:52
Have you looked at existing open issues?

**Comment by faraco** [comment] 2016-12-23 14:07
I don't see any that is similar to thi.

**Comment by justinmayer** [comment] 2016-12-23 15:23
Dupe of #2043. Pull request #2068 is pending.

**Closed by justinmayer** 2016-12-23 15:23 UTC

**Comment by faraco** [comment] 2016-12-23 15:26
alright thanks

**Comment by justinmayer** [comment] 2017-01-10 21:59
Pelican 3.7.1 has been released, containing a fix for this problem. Apologies for any frustration caused!
