### ISSUE TITLE
Inline SVG with a TITLE element causes corrupted HTML

### ISSUE THREAD

**Issue by bberberov** [getpelican/pelican#2561] opened 2019-04-24 18:40 UTC
**Steps to reproduce:**

1. Create an HTML content file
2. Add an inline SVG with a `title` element
3. Generate output

**Results:**

It appears the entire content of the body is injected into the `title` within the `head`, up to the closing `title` tag within the inline SVG.

**Comment by avaris** [comment] 2019-04-24 20:20
Confirmed and briefly checked the code. I *think* [this line](https://github.com/getpelican/pelican/blob/master/pelican/readers.py#L410) should be:
```python
elif tag == 'title' and self._in_head:
```

**Comment by stuaxo** [comment] 2019-10-08 11:03
Looks good to me, minor nit, but I'd reverse the order for this to make it consistent with the check for body tag, then content in the body, below.

It looks like this would need some new test data, e.g.   `article_with_line_svg.html` and a new test in `HTMLReaderTest`.

**Comment by stuaxo** [comment] 2019-10-10 23:40
Cheers - I was at work so I couldn't make a PR.

I've started the PR above, with a test for the inline SVG, need to work out how to make the remaining tests pass next.

**Comment by avaris** [comment] 2019-10-12 03:09
@stuaxo thanks for the PR. Reason for failing tests is that your new test article isn't included in [this](https://github.com/getpelican/pelican/blob/master/pelican/tests/test_generators.py#L240-L283) and [this](https://github.com/getpelican/pelican/blob/master/pelican/tests/test_generators.py#L240-L283) list.

**Comment by stuaxo** [comment] 2019-10-14 19:34
Cheers, updated.

**Comment by justinmayer** [comment] 2019-10-17 18:08
This was addressed in the just-released [Pelican 4.2](https://github.com/getpelican/pelican/releases/tag/4.2.0). ✨

**Closed by justinmayer** 2019-10-17 18:08 UTC
Labels: bug
