### ISSUE TITLE
[Feature Request] Auto refresh website after regenerated HTML in debug mode.

### ISSUE THREAD

**Issue by loggerhead** [getpelican/pelican#2092] opened 2017-01-22 08:59 UTC
Currently, pelican will regenerates HTML when markdown files changes, but the website will not auto refresh, which is not convenient. I found [moo](https://github.com/pyrocat101/moo) (a markdown live previewer) implemented this feature, so I think it's great if pelican can implement it too. The details of moo can see below:

* [server side](https://github.com/pyrocat101/moo/blob/master/moo/__init__.py#L121-L140)
* [javascript codes](https://github.com/pyrocat101/moo/blob/master/moo/static/app.js)

**Comment by justinmayer** [comment] 2017-01-23 16:24
Dupe of #1326. Feel free to help out by building on #1538 or by submitting a new implementation via pull request.

**Closed by justinmayer** 2017-01-23 16:24 UTC
