### ISSUE TITLE
<p> tag surrounding article.summary and page.summary

### ISSUE THREAD

**Issue by ghost** [getpelican/pelican#1271] opened 2014-02-22 22:05 UTC
<p class="first last"> surrounds article.summary and page.summary. Causes problems if looking to use the summary in a meta tag or you want to control what surrounds the data. Creates the requirement to modify your theme to use a filter to strip these tags out — i.e.: `{{ article.summary|striptags }}`

(*Edited by @justinmayer to clarify the provided interim workaround*)

**Comment by leotrs** [comment] 2016-08-14 15:35
@justinmayer this should also be closed.

**Comment by justinmayer** [comment] 2016-09-30 13:18
Ostensible dupe of closed issue #887.

**Closed by justinmayer** 2016-09-30 13:18 UTC
