### ISSUE TITLE
pelican --autoreload --listen OSError: [WinError 87]

### ISSUE THREAD

**Issue by dotoscat** [getpelican/pelican#2700] opened 2020-02-29 19:36 UTC
Windows 10
Python 8.2
Pelican 4.2.0

When I do this in powershell:

_> pelican --autoreload --listen_

This appears:

_CRITICAL: TypeError: cannot pickle 'generator' object
PS D:\proyectos\oscartrigarmatica> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\user\appdata\local\programs\python\python38\lib\multiprocessing\spawn.py", line 102, in spawn_main
    source_process = _winapi.OpenProcess(
OSError: [WinError 87] The parameter is incorrect_

**Comment by justinmayer** [comment] 2020-02-29 19:57
Duplicate of #2400. Please check open issues before filing new ones. Thanks.

**Closed by justinmayer** 2020-02-29 19:57 UTC
