### ISSUE TITLE
drafts index page renders with incorrect links to draft articles if it doesnt have a trailing /

### ISSUE THREAD

**Issue by johnmathews** [getpelican/pelican#2841] opened 2021-01-07 11:50 UTC
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: MacOS 11.0.1
- **Python version**: 3.8.5
- **Pelican version**: 4.5.3
- **Link to theme**: my own theme
- **Links to plugins**: 
nb_markup,
'neighbors',
'pelican.plugins.render_math',
'pelican.plugins.sitemap',
'pelican.plugins.simple_footnotes',
'pelican.plugins.more_categories',
- **Link to your site**: [johnmathews.eu](https://johnmathews.eu)
- **Link to [Gist](https://gist.github.com/johnmathews/703ac149ba3bf4e53290514bbec7d561) of local settings file

## Issue
in my local settings file I have the following settings for viewing drafts (i believe this is the default)
``` python
DRAFT_SAVE_AS = 'drafts/{slug}.html'
DRAFT_URL = 'drafts/{slug}.html'
```
I launch a local server with: `pelican --listen --autoreload`

if I go to `localhost:8000/drafts` then I see the correct (complete) list of hyperlinks to each draft article, but the link urls are wrong. they are `localhost:8000/<article-slug>.html` but they should be `localhost:8000/drafts/<article-slug>.html`

If however, i goto `localhost:8000/drafts/` (note the trailing `/`) then the links are correct and clicking on them sends the browser to the article.

Notwithstanding the incorrect links, the drafts index page seems to be identical in both cases.

This seems like a bug to me, but perhaps I've done something weird that I haven't spotted?

**Comment by avaris** [comment] 2021-01-07 17:52
I'd check the relevant templates. Make sure they are in [this form](https://github.com/getpelican/pelican/blob/659c4cbf0f0cd823d5eb199220e5a087f167733d/pelican/themes/notmyidea/templates/index.html#L11): note the explicit `/` between `SITEURL` and content URL.

**Comment by johnmathews** [comment] 2021-01-07 21:31
I'm not using any templates for the drafts index view.

**Comment by avaris** [comment] 2021-01-08 00:48
Oh, you mean the default directory listing (the one you get without an index). Yes, I can replicate that. Trying with `python -m http.server`, seems like `localhost:8000/drafts` triggers a redirect to `localhost:8000/drafts/` which makes things "work".  We do override `GET` so, we might need to replicate that behavior.

**Comment by adiroiban** [comment] 2021-10-04 16:58
I think that the fix for this is to have the embedded HTTP server enabled by ` --listen` do an automatic redirect from `/draft` to `/draft/` if 'draft' is a directory.

**Comment by avaris** [comment] 2021-10-04 20:19
So the issue is:

* Browser does `GET /drafts`
* Server happily resolves it as `GET /drafts/`
* Python server sees this and prepares a directory listing page
* Directory listing lists files with *relative urls*
* Browser looking at URL (still `/drafts`) considers the links as *sibling* instead of *child* since URL doesn't end with `/`

One solution is to redirect browser to `/drafts/` then the links would be interpreted correctly.

We can let `http.server` default kick in and do its job, but annoyingly it does `301 Permanent Redirect`. That sounds quite permanent for a temporary local server. 301s usually get cached in browser. So every time you type `http://localhost:8000/drafts` browser would "helpfully" do `Nope, that was moved. I'm changing that to http://localhost:8000/drafts/`.

Alternatively, we roll out our own redirect with `302 Found/Temporary redirect`. That is slightly more involved than what I was hoping for.

Another solution is that we just make our own directory listing with absolute URLs.

**Comment by adiroiban** [comment] 2021-10-04 22:12
I think that doing a redirect is good enough. No need for custom directory listing.
And a redirect might be  closer to that you will get with a production server.

Either using the default `http.server` 301 or a custom 307 is better than the current behavior.

**Closed** 2021-10-05 04:12 UTC
Labels: bug
