### ISSUE TITLE
extending from !theme only works for simple theme

### ISSUE THREAD

**Issue by copperchin** [getpelican/pelican#2745] opened 2020-04-29 06:58 UTC
Pelican version:  4.2.0 
Installed with pip into a virtualenv (Python 3.7.0)

It appears that only the "simple" theme can be extended from, while I suspect the intention was to be able to extend any theme installed with pelican-themes.  Even the default "notmyidea" theme cannot be extended in the way shown in the documentation.

Simple example:
`pelicanconf.py`
```
THEME = 'theme/'
DELETE_OUTPUT_DIRECTORY = True
```

`theme/templates/base.html`:
```
{% extends "!notmyidea/base.html" %}
```

Running `pelican` then results in 
```python
CRITICAL: TemplateNotFound: !notmyidea/base.html
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "[REDACTED]\env\py37\Scripts\pelican.exe\__main__.py", line 7, in <module>
  File "[REDACTED]\env\py37\lib\site-packages\pelican\__init__.py", line 570, in main
    pelican.run()
  File "[REDACTED]\env\py37\lib\site-packages\pelican\__init__.py", line 137, in run
    p.generate_output(writer)
  File "[REDACTED]\env\py37\lib\site-packages\pelican\generators.py", line 688, in generate_output
    self.generate_pages(writer)
  File "[REDACTED]\env\py37\lib\site-packages\pelican\generators.py", line 597, in generate_pages
    self.generate_articles(write)
  File "[REDACTED]\env\py37\lib\site-packages\pelican\generators.py", line 469, in generate_articles
    url=article.url, blog=True)
  File "[REDACTED]\env\py37\lib\site-packages\pelican\writers.py", line 278, in write_file
    override_output)
  File "[REDACTED]\env\py37\lib\site-packages\pelican\writers.py", line 210, in _write_file
    output = template.render(localcontext)
  File "[REDACTED]\env\py37\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "[REDACTED]\env\py37\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "[REDACTED]\env\py37\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "[REDACTED]\env\py37\lib\site-packages\pelican\themes\simple\templates\article.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "[REDACTED]\theme\templates\base.html", line 1, in top-level template code
    {% extends "!notmyidea/base.html" %}
jinja2.exceptions.TemplateNotFound: !notmyidea/base.html
```

But changing `theme/templates/base.html` like so:
```
{% extends "!simple/base.html" %}
```
Gives no errors when running `pelican` and behaves as expected (as shown in the documentation).

What's curious is that the trace indicates that the "simple" theme is still being referenced somehow (`simple\templates\article.html`).

The next thing I tried was adding this to the `pelicanconf.py`:
```
THEME_TEMPLATES_OVERRIDES = [
    "env/py37/lib/site-packages/pelican/themes/notmyidea/templates/"
]
```
Regenerating the site no longer produced an errors, but it also appears that now:
  * the files in my `theme/static` folder were copied to `output/theme` (good, same as before)
  * the static files from the override theme ("notmyidea") were NOT copied to `output/theme` (makes sense, but was unexpected)
  * the templates in my `theme/templates` folder were ignored entirely.  I could enter absolute garbage text in there and it made no difference. (not great)

So anyway, `THEME_TEMPLATES_OVERRIDES` doesn't appear to be the answer, but I'm not sure what is.  Is it possible to extend any themes besides "simple"?

**Comment by justinmayer** [comment] 2020-04-29 07:34
Hi Ryan. I understand what you're trying to accomplish and appreciate the detailed write-up. For maintainers, it's tough to juggle duplicate issues, so it's always best to first search for and read existing issues before filing new ones. In this case, _literally_ the issue filed just before this one is about the same topic (#2744), and that one is a duplicate of another (albeit closed) issue (#1092).

If theme inheritance in Pelican is something you are interesting in working on improving, we would welcome your contributions toward that endeavor. I'm going to close this issue, re-open the original issue, and see whether you (and perhaps other folks) are interested in moving this forward.

**Closed by justinmayer** 2020-04-29 07:34 UTC

**Comment by copperchin** [comment] 2020-04-29 16:16
Ha, that's uncanny!  Apologies: I did look through existing issues, but I must have filtered out closed issues, so never got any hits on this.  I might not get to this for a while, but I think it's something worth poking at down the road.

**Comment by justinmayer** [comment] 2020-04-29 16:18
No worries. Thanks for understanding. Hoping you can find the time to help make this a reality. Cheers!

**Comment by copperchin** [comment] 2020-09-14 16:51
I see this is closed now, but I'm going to start poking around and see what can be done about theme inheritance.

**Comment by copperchin** [comment] 2020-09-14 18:04
Right, sorry, just getting back up to speed here; I see the [original issue](https://github.com/getpelican/pelican/issues/1092) was reopened, so I'll jump over there.

**Comment by bison--** [comment] 2024-12-22 00:38
Using 4.10.2 and i was trying to do the same, extend the head of the "notmyidea" theme but it doesn't seem to work, so I ended up here. I tried to understand what's going on but I cant get my head around if it is solved/merged or still not possible.

**Comment by justinmayer** [comment] 2024-12-22 10:40
As far as I am aware, nobody has volunteered to implement the arbitrary theme inheritance described in the above-linked issue (1092). It has been over a decade since that issue was submitted, which is why that issue is closed. Nonetheless, anyone who is willing to implement this feature is welcome to post a comment in that issue to communicate that intention, and pull requests that implement that feature would be very welcome.
