### ISSUE TITLE
Makefile always create all tasks 

### ISSUE THREAD

**Issue by hmleal** [getpelican/pelican#2000] opened 2016-08-29 19:25 UTC
When i use quickstart to initiate to start new project Makefile is created with always create all tasks even i answered that I will not use things like:
- ssh_upload
- rsync_upload
- dropbox_upload
- ftp_upload
- s3_upload
- cf_upload

**Comment by GregHilston** [comment] 2016-08-30 23:58
Can you provide me the version of pelican you're using along with walk me through your answers to each of the quick start questions?

I just ran through the quick-start and was not able to reproduce your issue.

**Comment by medwards** [comment] 2016-09-06 19:14
pelican --version gives 3.6.3

Until I saw this issue I thought creating all the make targets was the expected behaviour, and they would just be unconfigured and broken XD

Here's what I just did:
1. /tmp/foo
2. Foo
3. Bar
4. `enter`
5. `enter`
6. http://example.com
7. n
8. Europe/Berlin
9. `enter`
10. `enter`
11. `enter1
12. y
13. `enter`
14. `enter`
15. `enter`
16. /var/www/foo
17. `enter`
18. `enter`
19. `enter`
20. `enter`

And I get make targets: ssh_upload, rsync_upload, dropbox_upload, ftp_upload, s3_upload, cf_upload, and github.

**Comment by justinmayer** [comment] 2016-09-06 21:01
> Until I saw this issue I thought creating all the make targets was the expected behaviour, and they would just be unconfigured and broken.

That is most likely correct. The idea was probably that if you aren't using those options, you won't be calling those targets, and thus it doesn't matter whether they work or not.

**Comment by GregHilston** [comment] 2016-09-06 21:14
I was thinking the best way for me to start contributing to Pelican would be to try and solve some issues. I'm thinking if I can figure this out and ensure only the files asked to be generated would actually be generated, that might be a great entry level difficulty. I'll report back.

**Comment by justinmayer** [comment] 2016-09-11 14:32
Thanks, Greg. Looking forward to hearing how it goes.

**Comment by justinmayer** [comment] 2016-09-30 12:07
Hi Greg. How is this coming along? Any updates?

**Comment by GregHilston** [comment] 2016-09-30 13:22
@justinmayer Hey, this actually slipped my mind. I'll be tackling it today and throughout the weekend. The first time I sat down to look at this, the source code was slightly intimidating as I'm no expert in Python. I'll report back with what I find. I apologize about the delay

**Comment by justinmayer** [comment] 2016-10-08 15:55
Hi Greg. Just checking in. How goes it?

**Comment by justinmayer** [comment] 2016-10-16 20:22
Any updates, Greg?

**Comment by GregHilston** [comment] 2016-10-17 23:48
Hey Justin, I wanted to apologize. I don't believe I'll be able to contribute right now. I thought I was going to previously and had every intention to do so, but have too many things going on right now. Sorry about the delay and the let down. Thanks for involving me though, I hope to someday help Pelican.

**Comment by justinmayer** [comment] 2016-10-18 23:33
No worries. Thanks for letting us know, Greg.

@hmleal / @medwards: Might you be willing to work on this issue?

**Comment by medwards** [comment] 2016-10-19 08:23
Nope. I agree with the maintainer that users know which make target they
need and using broken make targets would be weird. I'm a
garbage-in-garbage-out kind of guy.

**Comment by hmleal** [comment] 2016-10-19 15:43
yes i do in the next days ;)

**Comment by jonathansp** [comment] 2016-10-19 17:01
I have to agree with @hmleal. It doesn't make sense at all. By creating targets that wouldn't work could be confusing and useless.

**Comment by leotrs** [comment] 2016-12-13 18:07
I agree, creating unnecessary targets is confusing. I ended up deleting mine by hand at some point.
@hmleal Any progress?

**Comment by ix5** [comment] 2017-01-14 14:06
Why pelican has to use templates in weird autoconf syntax is beyond me, but that is not the point of this discussion.

What do you think of this concept: https://github.com/ix5/pelican/commit/66c98103411cf7133a512b633ae94b24486edc4a?
The approach:
- The python `string.Template` class is very limited(difficult for multiline placeholders) and uses the `re` module under the hood for `safe_substitute()`
- Introduce `{#` and `#}` as opening and closing delimiters in templates
- Also update `PROVIDERS` on each user input concerning `ssh`, `dropbox` etc.
- Use `re.sub()` to hide or show sections

This way,
```make
{#ssh
github:
    do_stuff
#}
```
becomes
```make
ssh:
    do_stuff
```
or disappears entirely, depending on `PROVIDERS.get('github')`.

Using some templating engine like mako would be overkill for an action the user ideally only does once.

This way sure ain’t pretty, and will be a nightmare for future more complex scenarios. Someone will have to come up with a more elegant way, but at least this approach does not introduce new dependencies.

**Comment by avaris** [comment] 2017-01-14 15:39
`pelican` already uses a template engine: `jinja`. Feel free to use it. No new dependency required.

**Comment by ix5** [comment] 2017-01-15 07:53
Hmm, yeah that is a good idea @avaris.
I've re-implemented the functionality in jinja2 here: https://github.com/ix5/pelican/commit/eef7d5fb8e8f38670cee1150ac254d39e3799add

(The additional newlines inside the conditional blocks are for whitespace control, `trim_blocks` is turned on)

**Comment by justinmayer** [comment] 2017-03-21 01:01
@ix5: Do you want to submit a pull request based on your work?

**Comment by ix5** [comment] 2017-03-21 12:49
Sure, [here](https://github.com/getpelican/pelican/pull/2122)

**Comment by ix5** [comment] 2018-02-11 12:20
Should be fixed by #2122, so this can be closed.

**Comment by justinmayer** [comment] 2018-02-11 18:32
Thanks, @ix5.

**Closed by justinmayer** 2018-02-11 18:32 UTC
