### ISSUE TITLE
Warn when encountering `.md` file without Markdown installed

### ISSUE THREAD

**Issue by Psycojoker** [getpelican/pelican#1868] opened 2015-11-18 20:58 UTC
Hello,

Currently, pelican will skip <code>.md</code> files if the "markdown" python packge is not installed. This result in a <code>WARNING: No valid files found in content."</code> which is **extremely** confusing and has made me lost 30min of debugging.

A better behavior would be to print a warning because there isn't a situation where a user would add a <code>.md</code> file to his content/ while not wanting it to be parsed.

Kind regards,

**Comment by avaris** [comment] 2015-11-18 22:10
Even though the [documentation](http://docs.getpelican.com/en/3.6.3/install.html#optional-packages) is **extremely** clear on that?

**Comment by Psycojoker** [comment] 2015-11-19 03:39
Well, the python adage as always been "explicit is better than implicit", in this case you have no indication that there might be a problem, it just doesn't work, it's a bit like saying "oh you need to set up this environment variable for this to be working", it wipes out the possibility of self discovery which is, for **me**, a bad practice, documented or not.

**Comment by ingwinlu** [comment] 2015-11-19 11:44
@Psycojoker if you need 30min to look up the documentation and find a solution then that is a documentation problem. [However I think it is reasonably good at explaining the issue.](http://pelican.readthedocs.org/en/latest/faq.html#i-want-to-use-markdown-but-i-got-an-error)

As for more warnings regarding the content when no Markdown Parser is available:
Currently pelican is only looking for files of certain extensions when their reader is activated. If no markdown is available, .md files are not even looked at and are 'invisible' to pelican.
I think that is great, it is one of the few occasions where pelican is actually abstracted well and can easily be extended or modified to only use a subset of readers that is needed.

Your suggestion would have implications for everyone who does not want to use markdown. Actually scanning the content directory for .md files when just using .rst could be a huge time waste for large sites with lots of content files.

A better alternative could be to print the active Readers and their supported file endings when starting up pelican, but again, this is probably not information you want to see on every run and would rather hide it to the debug menu in case 'no valid content' warning is not triggered.

Your usage of **fat** formatting and the way you phrase your comments makes you sound like a prig. When I first read it I wanted to react similarly to @avaris.

**Comment by Psycojoker** [comment] 2015-11-19 13:55
> A better alternative could be to print the active Readers and their supported file endings when starting up pelican, but again, this is probably not information you want to see on every run and would rather hide it to the debug menu in case 'no valid content' warning is not triggered.

If find the "only active when 'no valid content' case is encounter" to be a good middle ground. In my head you were using something like os.walk which would have allowed this operation without to much overhead since you would have been scanning all file names.

> Your usage of fat formatting and the way you phrase your comments makes you sound like a prig. When I first read it I wanted to react similarly to @avaris.

Sorry, the opposite was actually intent, as in "this is only my opinion which my not be the best opinion", I should have made it clearer to avoid ambiguity, my apologies :/

**Comment by avaris** [comment] 2015-11-19 14:58
We use `os.walk` to scan files, but we filter it to the ones `pelican` *can* process. That is obtained from the active readers. And missing dependencies isn't the only way to disable a reader (see `READERS` config).

Also, people might put `.md` files in their content simply as a static file. Just the existence of an `.md` file isn't as clear an indication as it might seem.

Having said that, listing active readers in debug log is a reasonable idea.

**Comment by cpitclaudel** [comment] 2016-05-01 19:10
What about replacing "WARNING: No valid files found in content" by "WARNING: No valid files found in content (did you forget to install a language support plugin?)"

**Comment by leotrs** [comment] 2016-08-20 16:32
There appears to be consensus on @cpitclaudel's suggestion and it looks like a pretty straightforward change.

**Comment by adrinjalali** [comment] 2016-10-13 11:38
> What about replacing "WARNING: No valid files found in content" by "WARNING: No valid files found in content (did you forget to install a language support plugin?)"

Plus maybe a link or a hint to the part in the documentation? I have to google the error everytime, come to such a thread, and figure the problem. Specially since many people including me, think of __pelican__ as something which handles `.md` files by default.

**Comment by justinmayer** [comment] 2016-10-16 20:28
@adrinjalali: [This is](http://docs.getpelican.com/en/stable/quickstart.html#installation) mentioned [over](http://docs.getpelican.com/en/stable/content.html#file-metadata) and [over](http://docs.getpelican.com/en/stable/faq.html#i-want-to-use-markdown-but-i-got-an-error) again in the docs. I'm fine with adding more descriptive error-handling, but IMHO this is not a documentation problem.

**Comment by adrinjalali** [comment] 2016-10-16 21:17
@justinmayer: oh yeah absolutely. I agree that the documentation couldn't be more explicit. I'm also talking about the warning message.

**Comment by justinmayer** [comment] 2016-10-16 21:18
Ah, re-reading your comment, I now understand what you meant. Apologies for the misunderstanding. 😅

**Comment by ChrisJefferson** [comment] 2017-05-07 15:22
The problem with the docs is that I if I see "no content found", my assumption is not that I should be looking at the docs about which directories are searched, or that I've put things in the wrong directories.

How about "no restructedText content found", where we make a list of the language parsers we ran. Then I would see that it isn't even looking for markdown.

**Comment by avaris** [comment] 2017-05-07 15:52
OK, we can elaborate the warning. How about:

```
WARNING: No valid files found in content for the active readers:
 | RstReader (.rst)
 | HTMLReader (.html, .htm)
...
```

**Comment by adrinjalali** [comment] 2017-05-07 16:15
Looks perfect to me (thumbsup)

**Comment by justinmayer** [comment] 2018-03-23 12:19
Would anyone in this thread like to help out by implementing the suggestion @avaris proposed?

**Comment by adrinjalali** [comment] 2018-03-23 14:01
You mean something like this commit @justinmayer ?
https://github.com/adrinjalali/pelican/commit/be4e04f774f779965e3fefea21995a4c9337af4e

example output:
```
WARNING: No valid files found in content for the active readers:                                                                                                                                                   
WARNING:  | BaseReader (static)                                                                                                                                                                                    
WARNING:  | RstReader (rst)                                                                                                                                                                                        
WARNING:  | HTMLReader (htm, html)   
```

**Comment by justinmayer** [comment] 2018-03-23 14:05
@adrinjalali: Perhaps a single `WARNING` in the output, as @avaris suggested above?

**Comment by adrinjalali** [comment] 2018-03-23 14:24
Changed the warning, now it shows:

```
WARNING: No valid files found in content for the active readers:                                                                                                                                                   
  | HTMLReader (htm, html)                                                                                                                                                                                         
  | BaseReader (static)                                                                                                                                                                                            
  | RstReader (rst)
```

**Comment by adrinjalali** [comment] 2018-03-23 15:41
Although, I'd prefer this implementation, up to you.

https://github.com/adrinjalali/pelican/compare/master...adrinjalali:issue89

**Comment by justinmayer** [comment] 2018-08-03 13:09
Addressed via #2310. Thanks again to Adrin for the enhancement!

**Comment by terrycojones** [comment] 2019-04-25 20:37
I realize this issue is closed & the above has been merged. I just ran into this situation and ended up solving it by coming here and reading the thread - despite the error message and he documentation, etc. So I could have done more, for sure, but I still think the error processing / message could be clearer. I'd suggest looking at the elements of the `MARKUP` list and trying an import based on what's in that list. That way you could issue an error like "You have listed 'md' in your MARKUP variable but you don't have the markdown module installed." and maybe even say something like "Did you forget to run `pip install markdown`?"

There's a bit of a "blame-the-user" feel to this thread...

**Comment by avaris** [comment] 2019-04-25 23:46
Which `MARKUP` variable? `pelican` doesn't use a `MARKUP` variable.

**Comment by terrycojones** [comment] 2019-04-26 08:09
Ah... sorry! I guess that was something used in older versions and that has been removed. In my `pelicanconf.py` I have

```python
MARKUP = ('md', 'ipynb')
```
If it was still a thing (or maybe it has been renamed?) I was thinking it could provide a way to avoid  walking the filesystem looking for (in this case) `.md` files, etc. Thanks @avaris & sorry for the noise!

**Comment by avaris** [comment] 2019-04-26 13:22
Yeah, there is no setting like that. Extensions to process are obtained from active readers.

BTW, I am slightly inclined to blame the user :). Even searching for `"No valid files found in content"` gets you the relevant information in the first hit... But, will extending warning a bit more be helpful? Something like:
```
> pelican content
WARNING: No valid files found in content
  | Active readers:
  |  * BaseReader (static)
  |  * HTMLReader (htm, html)
  |  * RstReader (rst)
  |
  | Inactive readers (explicitly deactivated or missing dependency):
  |  * MarkdownReader (md, markdown, mkd, mdown)
Done: Processed 0 articles, 0 drafts, 0 pages, 0 hidden pages and 0 draft pages in 0.07 seconds.
```

**Comment by terrycojones** [comment] 2019-04-26 13:48
Yes, that looks good. I don't think this should be a high priority, just something that could be a bit nicer.

And, I know the temptation (re users)  Most of the time I like it when there are no (other) users :-)  Thanks for all the work on Pelican!

**Comment by bjinse** [comment] 2019-12-15 10:27
I had the same issue as terrycojones. Migrated to a new machine, installed pelican, but no markdown (yet). Did a make command to generate AND publish. Poof, website content was all gone... Should have been a bit more careful.
Luckily I found this thread within a minute.
Thumbs up for explicitly stating markdown is not installed.
Maybe especially if (like in my case) markdown files are found in the content dir.

**Comment by kaddkaka** [comment] 2021-11-12 18:09
> Even though the [documentation](http://docs.getpelican.com/en/3.6.3/install.html#optional-packages) is **extremely** clear on that?

Is is not extremely clear, the quickstart guide mentions nothing about it.

**Comment by avaris** [comment] 2021-11-12 19:01
@kaddkaka Which quickstart are you looking at? It's mentioned right at the [start](https://docs.getpelican.com/en/4.7.1/quickstart.html#installation):

> Install Pelican (and optionally Markdown if you intend to use it) ...

**Comment by JBacc1** [comment] 2022-02-08 19:34
For what it's worth, I did not find the error message particularly explicit (something mentioning markdown and/or pip install would have helped).
`WARNING  No valid files found in content for the active      log.py:91
                    readers:                                                     
                      | BaseReader (static)                                      
                      | HTMLReader (htm, html)                                   
                      | RstReader (rst)`

**Comment by Axeltherabbit** [comment] 2022-03-17 21:03
I'm just trying pelican, I didn't go deeply in the docs yet and just read a short guide with commands, I haven't wasted 30 minutes because I found this issue in 30 secs but I agree with @JBacc1 adding something "maybe you need markdown installed if you are using .md files" in the warning would not be a big issue and help

**Comment by szhorvat** [comment] 2024-01-05 22:19
Version 4.9.1 does not give any sort of warning that would indicate what is wrong. Previous versions did. I just wasted an hour because of this. Yes, there should be a clear warning.

**Comment by opokatech** [comment] 2024-03-24 16:23
I've just fell into the same trap by helping someone with the pelican (helping with making a git repo, requirements.in/txt, makefile). It worked well on her machine (because she installed markdown manually and forgot about it), but not on mine, because _I did not read the doc_ and did not know that markdown must be installed. It took several frustrating minutes to find that out.

At the end of generating process I could see only this:

`Done: Processed 0 articles, 0 drafts, 0 hidden articles, 0 pages, 0 hidden pages and 0 draft pages in 0.05 seconds.`

It would be very helpful, in case when literaly nothing was processed (all counters == 0), to issue some extra textual hint like
`Nothing processed, see the quickstart for help: https://docs.getpelican.com/en/latest/quickstart.html`

And there it is clearly visible that markdown is necessary.

**Comment by justinmayer** [comment] 2024-03-24 18:36
It appears some kind of regression has indeed occurred. Output on 4.8.0:

```
➤ pelican content
[19:29:13] WARNING  Watched path does not exist: ~/.virtualenvs/tempenv-17791136813a0/content/images                                                        log.py:91
           WARNING  No valid files found in content for the active readers:                                                                                         log.py:91
                      | BaseReader (static)
                      | HTMLReader (htm, html)
                      | RstReader (rst)
Done: Processed 0 articles, 0 drafts, 0 hidden articles, 0 pages, 0 hidden pages and 0 draft pages in 0.03 seconds.
```

---------------------------------------

Output on 4.9.1:

```
➤ pelican content
Done: Processed 0 articles, 0 drafts, 0 hidden articles, 0 pages, 0 hidden pages and 0 draft pages in 0.03 seconds.
```

-----------------------------------------

This should either be addressed in a way that eliminates this persistent confusion, or we should add `markdown` as a standard dependency.

I know there has been resistance to the latter, but I'm guessing the vast majority of Pelican users are writing their content in Markdown, and I don't know whether it continues to make sense in 2024 to leave `markdown` as an optional dependency.

**Comment by MinchinWeb** [comment] 2024-03-26 05:08
>  I don't know whether it continues to make sense in 2024 to leave markdown as an optional dependency

I'm working on a CommonMark reader, so my that case, (Python) Markdown isn't needed. (it's probably usable now, if you want to check it out https://github.com/MinchinWeb/minchin.pelican.readers.commonmark )

Part of the reason I actually pushed ahead with this is we do already install Markdown as a required (transitive) dependency, but `markdown-it-py` by way of `rich`. So I figured I'd see if I could make use of it, since it was already installed.

Anyway, just my two bits on what I'm up to in my corner of the world with Pelican.

**Comment by avaris** [comment] 2024-04-19 18:30
> I know there has been resistance to the latter, but I'm guessing the vast majority of Pelican users are writing their content in Markdown, and I don't know whether it continues to make sense in 2024 to leave markdown as an optional dependency.

I may have been one of those resistors, by the virtue of trying to keep things slim. But I am happy to rescind my objection and I would be fine with making `markdown` a required dependency.

**Comment by justinmayer** [comment] 2024-04-19 19:01
I also value the virtue of having few required dependencies. For the moment, let's address the problem by fixing the regression and adding an even clearer message regarding what's happening and what users must do to proceed.

**Comment by boxydog** [comment] 2024-05-31 16:13
I also think adding `markdown` as a required dependency is a good option. It fixes the issue for the casual user, and is likely not too burdensome.

However, FYI I believe the regression was in 61ca47c5194f33ad28e96cf965ba9f582d6d7909, which removed the `check` function that produced the warning (see [this line](https://github.com/getpelican/pelican/commit/61ca47c5194f33ad28e96cf965ba9f582d6d7909#diff-2a731ae98cd07cade4485407264a8ce9cb0808dfc32a89e0e0c8e3f9b2d14aafL840)).

**Comment by boxydog** [comment] 2024-05-31 19:51
Filed #3321 to log warnings about files that would have been processed by disabled readers.

I think requiring markdown as a required dependency is easier, but I wanted to see what the other side looked like.

**Comment by justinmayer** [comment] 2024-06-25 13:50
Thanks to @boxydog, Pelican will now emit warnings when it encounters Markdown files without the [Python-Markdown](https://github.com/Python-Markdown/markdown) package installed. This feature is now in the Pelican `main` branch and will appear in a shipped release shortly.

**Closed by justinmayer** 2024-06-25 13:50 UTC
