### ISSUE TITLE
Move Markdown down to a plugin  of a new Convert class.

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#3344] opened 2024-06-22 17:20 UTC
- [x ] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [ x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [ x] I am willing to lend a hand to help implement this feature. 

## Feature Request
In light of the latest Markdown coming ahead called [Markdown-It](https://github.com/executablebooks/markdown-it-py/pulse), which is now **CommonMark**-compliant as well as GitHub Markdown as an extension, which supplanted the Markdown (MD1, MD2, MD3, MD4), MetaMarkdown (MMD), and sundown, we should consider the future plan of  supporting plugin-scheme for  such markdown formats.

I think  it would be helpful to start moving current  `Markdown`  package use by Pelican from an hardcoded approach toward a future-friendly plug-in approach thus making  it easier to take on various MD plugins.

(Unless I am missing some `pelicanconf.py` setting for disabling this hardcoded Markdown package somehow).

**Comment by MinchinWeb** [comment] 2024-06-23 03:32
Possible duplicate of https://github.com/getpelican/pelican/issues/2984

Switching the Markdown renderer can be done by writing a (Pelican) plugin, and as per #2984, seems to be the preferred solution.

If you don't have `markdown` installed, then the built-in renderer doesn't run.

As for the (Python) `markdown` package, it pre-dates CommonMark and doesn't consider itself replaced by it, and continues to be maintained.

**Comment by justinmayer** [comment] 2024-06-25 07:06
I believe @MinchinWeb summarized things very nicely. A few follow-up thoughts…
1. I think using terms like "hardcoded" is a bit misleading. As @MinchinWeb said, if the [Python-Markdown](https://github.com/Python-Markdown/markdown) package is not installed, then that Markdown renderer does not run. So there is no need to explicitly disable it.
2. As @MinchinWeb said (and has demonstrated), alternative Markdown parsers can already be supported via Pelican plugins.
3. [Python-Markdown](https://github.com/Python-Markdown/markdown) continues to be an excellent and well-maintained Markdown parser and is not in need of replacement for most people.
4. It seems to me that moving the current built-in support for [Python-Markdown](https://github.com/Python-Markdown/markdown) into a separate plugin would require considerable effort with uncertain benefit. If someone volunteers to undertake such an endeavor, we could discuss further.

**Comment by egberts** [comment] 2024-06-27 14:14
> I believe @MinchinWeb summarized things very nicely. A few follow-up thoughts…
> 
> 1. I think using terms like "hardcoded" is a bit misleading. As @MinchinWeb said, if the [Python-Markdown](https://github.com/Python-Markdown/markdown) package is not installed, then that Markdown renderer does not run. So there is no need to explicitly disable it.


Of course, this could be a problem if virtual environment is not being used if markdown package is installed for use by a non-Pelican application and one should desire not to use this particular Markdown package for Pelican. 

(That was my scenario, a pesky hassle but not an unsolvable one at that).

**Comment by egberts** [comment] 2024-07-04 19:15
> 3. [Python-Markdown](https://github.com/Python-Markdown/markdown) continues to be an excellent and well-maintained Markdown parser and is not in need of replacement for most people. It has a very rich [third-party extension eco-system](https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions) that as far as I can tell cannot be matched by any alternative Markdown parser ([including `markdown-it-py`](https://github.com/MinchinWeb/blog.minchin.ca/issues/133#issuecomment-2184486279)).

After reviewing the various alternatives to current Pelican's selection of Markdown, I agree that this suggested step should be deferred until "better outputter" get their customization made accessible (to Pelican, at least).

This means that my zeal to adding a more robust table plugin has become more desired. 

Closing this issue.

**Closed** 2024-07-04 19:18 UTC
Labels: enhancement
